"""initial uuid schema

Revision ID: 14cb4e59f010
Revises: 
Create Date: 2026-02-25 17:18:19.434081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14cb4e59f010'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_sessions_id'), 'scrape_sessions', ['id'], unique=False)
    op.create_table('scraped_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('raw_html', sa.Text(), nullable=False),
    sa.Column('selector', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['scrape_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scraped_pages_session_id', 'scraped_pages', ['session_id'], unique=False)
    op.create_index('idx_scraped_pages_url', 'scraped_pages', ['url'], unique=False)
    op.create_index(op.f('ix_scraped_pages_id'), 'scraped_pages', ['id'], unique=False)
    op.create_table('scraped_elements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('tag_name', sa.String(), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['scraped_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scraped_elements_page_id', 'scraped_elements', ['page_id'], unique=False)
    op.create_index(op.f('ix_scraped_elements_id'), 'scraped_elements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraped_elements_id'), table_name='scraped_elements')
    op.drop_index('idx_scraped_elements_page_id', table_name='scraped_elements')
    op.drop_table('scraped_elements')
    op.drop_index(op.f('ix_scraped_pages_id'), table_name='scraped_pages')
    op.drop_index('idx_scraped_pages_url', table_name='scraped_pages')
    op.drop_index('idx_scraped_pages_session_id', table_name='scraped_pages')
    op.drop_table('scraped_pages')
    op.drop_index(op.f('ix_scrape_sessions_id'), table_name='scrape_sessions')
    op.drop_table('scrape_sessions')
    # ### end Alembic commands ###
