"""initial tables

Revision ID: 67943dd815f6
Revises: 
Create Date: 2026-02-17 04:58:01.686549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67943dd815f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrape_sessions', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('scrape_sessions', 'url')
    op.drop_column('scrape_sessions', 'selector')
    op.add_column('scraped_elements', sa.Column('page_id', sa.Integer(), nullable=False))
    op.add_column('scraped_elements', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index('idx_scraped_elements_page_id', 'scraped_elements', ['page_id'], unique=False)
    op.drop_constraint(op.f('scraped_elements_session_id_fkey'), 'scraped_elements', type_='foreignkey')
    op.create_foreign_key(None, 'scraped_elements', 'scraped_pages', ['page_id'], ['id'], ondelete='CASCADE')
    op.drop_column('scraped_elements', 'html_content')
    op.drop_column('scraped_elements', 'attributes')
    op.drop_column('scraped_elements', 'position_index')
    op.drop_column('scraped_elements', 'session_id')
    op.add_column('scraped_pages', sa.Column('session_id', sa.Integer(), nullable=False))
    op.add_column('scraped_pages', sa.Column('url', sa.String(), nullable=False))
    op.add_column('scraped_pages', sa.Column('raw_html', sa.Text(), nullable=False))
    op.add_column('scraped_pages', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index('idx_scraped_pages_session_id', 'scraped_pages', ['session_id'], unique=False)
    op.create_index('idx_scraped_pages_url', 'scraped_pages', ['url'], unique=False)
    op.create_foreign_key(None, 'scraped_pages', 'scrape_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scraped_pages', type_='foreignkey')
    op.drop_index('idx_scraped_pages_url', table_name='scraped_pages')
    op.drop_index('idx_scraped_pages_session_id', table_name='scraped_pages')
    op.drop_column('scraped_pages', 'created_at')
    op.drop_column('scraped_pages', 'raw_html')
    op.drop_column('scraped_pages', 'url')
    op.drop_column('scraped_pages', 'session_id')
    op.add_column('scraped_elements', sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('scraped_elements', sa.Column('position_index', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('scraped_elements', sa.Column('attributes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('scraped_elements', sa.Column('html_content', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'scraped_elements', type_='foreignkey')
    op.create_foreign_key(op.f('scraped_elements_session_id_fkey'), 'scraped_elements', 'scrape_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_scraped_elements_page_id', table_name='scraped_elements')
    op.drop_column('scraped_elements', 'created_at')
    op.drop_column('scraped_elements', 'page_id')
    op.add_column('scrape_sessions', sa.Column('selector', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('scrape_sessions', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('scrape_sessions', 'name')
    # ### end Alembic commands ###
