"""add selector and mode to scraped_pages

Revision ID: 711e3b67162b
Revises: 67943dd815f6
Create Date: 2026-02-25 12:36:38.061612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '711e3b67162b'
down_revision: Union[str, Sequence[str], None] = '67943dd815f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraped_pages', sa.Column('selector', sa.String(), nullable=True))
    op.add_column('scraped_pages', sa.Column('mode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraped_pages', 'mode')
    op.drop_column('scraped_pages', 'selector')
    # ### end Alembic commands ###
